language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

before_script:
  - pip install docker-compose
  - docker build -t django-rest-app:1.0.0 .

script:
  - docker-compose run app sh -c "python manage.py test && flake8"